### ISSUE TITLE
New genesis creation: export staged ledger

### ISSUE THREAD

**Issue by kantp** [MinaFoundation/mina#23]
With #21 and #22, we will have a way of getting consensus across the network about the final stage of the ledger pre hard fork.

The aim of this issue is to create a mechanism of exporting the staged ledger from the slot `slot-tx-end`.

**Comment by Sventimir** [comment]
[PR #13788](https://github.com/MinaProtocol/mina/pull/13768) in the MinaProtocol repo contains changes to the `berkeley` branch required to successfully parse a config file generated by a `compatible` node.

**Comment by Sventimir** [comment]
[PR #13768](https://github.com/MinaProtocol/mina/pull/13768) in the MinaProtocol repo contains a new GraphQL query which generates a configuration file containing the genesis ledger for the hard fork network.

**Comment by Sventimir** [comment]
The hard fork config is mostly done. The PR against `compatible` mentioned above is already merged. The other seems to be blocked by CI issues. Meanwhile, in order to write proper unit tests, we need to write some generators as stated in #38 .

**Comment by Sventimir** [comment]
The PR has now been merged and also is being ported to `berkeley` right now.
