### ISSUE TITLE
Stub Out Abstract Engine

### ISSUE THREAD

**Issue by ejMina226** [MinaFoundation/mina#34]
With the config/contract requirements crystallising, the Abstract Engine can start being written. Given that we wish to keep the existing integration tests as they are, I suggest sticking with having thee core files so that the engine interface is satisfied. We should stub out abstract equivalents of the following:
- [x] mina_automation.ml
- [x] kubernetes_network.ml
- [x] graph_ql_polling_log_engine.ml
- [x] parse config file
- [x] command line args
- [x] `run_command` function
- [x] `run_command` output interpretation
- [x] `abstract_engine.ml`
- [x] `test_executive.ml`
- [x] `mina_automation.ml`
- [x] command output spec in separate return spec
- [x] parsing command output specs
- [ ] Come up with better names for these modules

**Comment by ejMina226** [comment]
@Isaac-DeFrain is taking this over now.

**Comment by Isaac-DeFrain** [comment]
Draft PR https://github.com/MinaFoundation/mina/pull/35

**Comment by Isaac-DeFrain** [comment]
This turned into a enormous task
