### ISSUE TITLE
Nil bridge | Production

### ISSUE THREAD

**Issue by snaitmouloud-mf** [MinaFoundation/mina#77]
Audit

Staked ledger

optimisations

Upgrade path

**Comment by snaitmouloud-mf** [comment]
David.sedgwick commented: Road to Production proposal shared with MF.
VS to review Rust Node integation for auto-proof updates.
Phillip H carrying out testing of e2e (again) 

Next step, get the above concluded and work out if/how we work with Nil and current engagement and also future engagement

**Comment by TyrellCorp2020** [comment]
testing
