### ISSUE TITLE
Understand Initialize_infra and how it relates to mini_mina

### ISSUE THREAD

**Issue by ejMina226** [MinaFoundation/mina#79]

**Comment by ejMina226** [comment]
@Isaac-DeFrain  The `initialize_infra` function which sits (in GCP) in the kubernetes_network.ml repeatedly checks the status of the kubernetes pods that have been created/deployed. Presumably, this is a more uncertain process in terraform. In the abstract engine case this step might not be necessary as for minimina, at least, we're more in control - we want to ensure each mina node is assigned its own docker container, and this happens by default. However, thinking ahead to AWS we may want some kind of functionality in place. Since the `initialize_infra` method defined in the abstract engine case has to cover all environments, we should probably have a corresponding method in the config file for the network-runners and just have the abstract engine method be a wrapper about this. In the case of minimina it could do nothing, but in AWS have a function that will be called to check the kubernetes nodes. Is this clear? Thanks.

**Comment by Isaac-DeFrain** [comment]
Great! Thanks @ejMina226. If you want to take the charge on adding the config command and implementing handling in the abstract engine, go for it. You can use the existing examples in the abstract network as a guide
